default_context:
  project_name: 'Animal to Map'
  project_slug: 'animal-to-map'
  domain_main: 'animal-to-map.com'
  domain_staging: 'stag.animal-to-map.com'
  domain_base_api_url: 'http://animal-to-map.com/api/v1'
  domain_base_ws_url: 'ws://animal-to-map.com/api/v1'
  docker_swarm_stack_name_main: 'animal-to-map-com'
  docker_swarm_stack_name_staging: 'stag-animal-to-map-com'
  secret_key: 'animalix'
  first_superuser: 'admin@animal-to-map.com'
  first_superuser_password: 'admin'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.animal-to-map.com", "https://stag.animal-to-map.com", "https://animal-to-map.com"]'
  smtp_tls: 'False'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@animal-to-map.com'
  smtp_emails_from_name: 'John Doe'
  smtp_emails_to_email: 'info@animal-to-map.com'
  mongodb_uri: 'mongodb+srv://sample-user:Slalom.2004@cluster0.jus8f1l.mongodb.net/?appName=Cluster'
  mongodb_database: 'animals'
  traefik_constraint_tag: 'animal-to-map.com'
  traefik_constraint_tag_staging: 'stag.animal-to-map.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:admin'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/**/*.html, frontend/**/*.vue, frontend/.nuxt/*, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
